//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDocumentationConsole.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class enduser
    {
        public int id { get; set; }
        public string ad_name { get; set; }
        public string first_name { get; set; }
        public string mid_init { get; set; }
        public string last_name { get; set; }
        public string full_name { get; set; }
        public string email_name { get; set; }
        public string ad_active_flag { get; set; }
        public System.DateTime row_create_date { get; set; }
        public Nullable<System.DateTime> row_modify_date { get; set; }
        public string ad_account_name { get; set; }
        public string user_phone { get; set; }
        public string title { get; set; }
        public string department { get; set; }
        public Nullable<int> ad_user_account_control { get; set; }
        public int manager_enduser_id { get; set; }
        public string always_active_flag { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> deactivate_date { get; set; }
        public string active_flag { get; set; }
        public string user_fax { get; set; }
        public string user_cell { get; set; }
        public string user_phone_full { get; set; }
        public string business_street { get; set; }
        public string business_city { get; set; }
        public string business_state { get; set; }
        public string business_zip { get; set; }
        public int segment_id { get; set; }
        public int credit_enduser_id { get; set; }
        public Nullable<short> timezone_offset { get; set; }
        public string real_user_flag { get; set; }
        public string lp_initials { get; set; }
        public string lp_name { get; set; }
        public string lp_active { get; set; }
        public Nullable<long> aspire_entt_id { get; set; }
        public Nullable<decimal> buy_rate { get; set; }
        public Nullable<decimal> commission_pct { get; set; }
        public Nullable<System.DateTime> password_last_changed { get; set; }
        public string password_expired { get; set; }
        public string password_never_expires { get; set; }
        public Nullable<System.DateTime> password_expiration_date { get; set; }
        public string phone_ext { get; set; }
        public string title_alias { get; set; }
        public Nullable<int> primary_ad_role_id { get; set; }
        public Nullable<System.DateTime> hire_date { get; set; }
        public Nullable<System.DateTime> term_date { get; set; }
        public Nullable<bool> edocs_flag { get; set; }
        public Nullable<bool> edocs_approve_flag { get; set; }
        public string docmaide_email { get; set; }
        public Nullable<int> reporting_manager_id { get; set; }
        public string payquote_permission { get; set; }
        public string notification_emails { get; set; }
        public Nullable<bool> DST_Flag { get; set; }
    }
}
