//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDocumentationConsole.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportSP()
        {
            this.Report_ReportSP = new HashSet<Report_ReportSP>();
        }
    
        public int ID { get; set; }
        public string SPName { get; set; }
        public Nullable<bool> IsRDLDropdown { get; set; }
        public string PermissionsNotes { get; set; }
        public Nullable<System.DateTime> RowCreateDate { get; set; }
        public Nullable<int> CreateEnduserId { get; set; }
        public Nullable<System.DateTime> RowModifyDate { get; set; }
        public Nullable<int> ModifyEnduserId { get; set; }
        public Nullable<int> SSRSReportId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report_ReportSP> Report_ReportSP { get; set; }
    }
}
