//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDocumentationConsole.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSP
    {
        public int ID { get; set; }
        public Nullable<int> SSRSReportId { get; set; }
        public string SPName { get; set; }
        public Nullable<bool> IsRDLDropdown { get; set; }
        public string PermissionsNotes { get; set; }
        public Nullable<System.DateTime> RowCreateDate { get; set; }
        public Nullable<int> CreateEnduserId { get; set; }
        public Nullable<System.DateTime> RowModifyDate { get; set; }
        public Nullable<int> ModifyEnduserId { get; set; }
    }
}
