//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDocumentationConsole.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSPParameter
    {
        public int ID { get; set; }
        public int ReportSPId { get; set; }
        public string RDLParameterName { get; set; }
        public string ParamDescription { get; set; }
        public Nullable<bool> IsUserControlled { get; set; }
        public string UserControlType { get; set; }
        public Nullable<bool> IsSetValue { get; set; }
        public string DefaultValue { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<System.DateTime> RowCreateDate { get; set; }
        public Nullable<int> CreateEnduserId { get; set; }
        public Nullable<int> SSRSReportId { get; set; }
    }
}
