//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDocumentationConsole.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportChangeLog
    {
        public int ID { get; set; }
        public Nullable<int> SSRSReportId { get; set; }
        public Nullable<int> ReportSPId { get; set; }
        public Nullable<System.DateTime> RowCreateDate { get; set; }
        public string ITComment { get; set; }
        public string PublicComment { get; set; }
        public Nullable<bool> IsRDLChange { get; set; }
    }
}
