//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDocumentationConsole.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SsrsReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SsrsReport()
        {
            this.Report_ReportSP = new HashSet<Report_ReportSP>();
        }
    
        public int id { get; set; }
        public Nullable<int> reportcat_id { get; set; }
        public string rpt_name { get; set; }
        public string rpt_desc { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string sp_name { get; set; }
        public string RdlName { get; set; }
        public Nullable<int> OwnerEnduserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report_ReportSP> Report_ReportSP { get; set; }
    }
}
